### ISSUE TITLE
Rename file io/vtx.[ch] to io/vtxrc.[ch]

### ISSUE THREAD

**Issue by jflyper** [sblakemore/cleanflight#2]
@sblakemore 
I saw your work on separation of device independent things in io and drivers directory, which was on my work list also. Upon doing so, you have created vtx.[ch] in both io and drivers directory.

Why don't we change the ones in io directory to vtxrc.[ch]? They avoid name collisions, and better express what is inside of them, imo.

It may also be nice to change function/object names in these files from vtxXXX() to vtxRcXXX() for more clarity.

**Comment by sblakemore** [comment]
There are a couple of cases like this already, for example serial.[ch] and transponder_ir.[ch]. Seems like a reasonable change however, no real downside and can save some confusion.
