### ISSUE TITLE
Introduction of an compile time option VTXRC

### ISSUE THREAD

**Issue by jflyper** [sblakemore/cleanflight#3]
@sblakemore 
My initial use case was for micro builds where lots of people still use F1s in which space is a premium. For such targets, it would be nice to have an option to drop RC-based control and just use CLI variables to choose a TX frequency.

The option would be called VTXRC. Without VTXRC, init() will just call a VTX initialization function where the TX frequency is statically decided from vtx_{mode,band,channel,mhz}. With VTXRC, full RC-based control will be compiled in.

**Comment by sblakemore** [comment]
Seems reasonable to me, good idea!
